### ISSUE TITLE
npm start won't work

### ISSUE THREAD

**Issue by RaulTsc** [selfrefactor/react-chrome-extension-boilerplate#1]
```
 Tell the author that this fails on your system:
npm ERR!     browserify -t reactify contentscript.jsx -o contentscript.js&&browserify -t reactify options.jsx -o options.js
```

Node -v: 5.3.0
npm -v: 3.5.3

It seems something is fishy. I also don't seem to have browserify nor reactify in .bin.

**Comment by selfrefactor** [comment]
Hello Raul,

I see the issue now, I will see it soon and get back with the result

**Comment by selfrefactor** [comment]
Closing it now - works inside Cloud9 IDE.
Try running gulp, or start manually the "browserify -t reactify contentscript.jsx -o contentscript.js" and check the errors if such.
